FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY src/main.py src/main.py
COPY src/chatbot_api src/chatbot_api
COPY src/db src/db
COPY experiments/chatbot/echo_chatbot/resources experiments/chatbot/echo_chatbot/resources

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
