FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy your code
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

ENV APP_ENV=production

CMD ["python", "main.py"]

#dockerfile -(build)> docker image -(run)> docker container -> running application