services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
      args:
        HF_TOKEN: "${HF_TOKEN}"
    container_name: "${CHATBOT_CONTAINER_NAME:-echo-chatbot-api}"
    environment:
      APP_ENV: "production"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}"
      HF_TOKEN: "${HF_TOKEN}"
      HF_HOME: "/root/.cache/huggingface"
      GROQ_API_KEY1: "${GROQ_API_KEY1}"
      GROQ_API_KEY2: "${GROQ_API_KEY2}"
      JINA_API_KEY: "${JINA_API_KEY}"
      TAVILY_API_KEY: "${TAVILY_API_KEY}"
      R2_ACCOUNT_ID: "${R2_ACCOUNT_ID}"
      CF_AI_API: "${CF_AI_API}"
    ports:
      - "8000:8000"
    gpus: all

  video:
    build:
      context: .
      dockerfile: Dockerfile.video
      args:
        HF_TOKEN: "${HF_TOKEN}"
    container_name: "${VIDEO_CONTAINER_NAME:-echo-video-api}"
    environment:
      APP_ENV: "production"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}"
      R2_ACCOUNT_ID: "${R2_ACCOUNT_ID}"
      R2_ACCESS_KEY: "${R2_ACCESS_KEY}"
      R2_SECRET_KEY: "${R2_SECRET_KEY}"
      R2_BUCKET_NAME: "${R2_BUCKET_NAME}"
      HF_TOKEN: "${HF_TOKEN}"
      HF_HOME: /root/.cache/huggingface
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    volumes:
      - hf_cache_video:/root/.cache/huggingface
    ports:
      - "8001:8001"
    gpus: all

volumes:
  hf_cache_video:

# Run with: docker compose up --build
