"""Add indexes on pharaoh and landmark name columns

Revision ID: 11bfd0bf7c97
Revises: bf1e22447449
Create Date: 2026-03-22 01:18:17.765381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bfd0bf7c97'
down_revision: Union[str, None] = 'bf1e22447449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('hnsw_idx_landmark_image_embedding', 'landmark_images', ['image_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    op.create_index('idx_landmarks_name', 'landmarks', ['name'], unique=False)
    op.create_index('idx_pharaohs_name', 'pharaohs', ['name'], unique=False)
    op.create_index('hnsw_idx_pharaoh_image_embedding', 'pharaohs_images', ['image_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hnsw_idx_pharaoh_image_embedding', table_name='pharaohs_images', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_pharaohs_name', table_name='pharaohs')
    op.drop_index('idx_landmarks_name', table_name='landmarks')
    op.drop_index('hnsw_idx_landmark_image_embedding', table_name='landmark_images', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
