"""create landmarks and pharaohs tables

Revision ID: 19df57864a03
Revises: 
Create Date: 2026-02-23 02:50:40.532783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '19df57864a03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    """Upgrade schema.""" 
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmarks_id'), 'landmarks', ['id'], unique=False)
    op.create_table('pharaohs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dynasty', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharaohs_id'), 'pharaohs', ['id'], unique=False)
    op.create_table('landmark_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('is_builder', sa.Boolean(), nullable=True),
    sa.Column('is_plan', sa.Boolean(), nullable=True),
    sa.Column('is_location', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmark_images_id'), 'landmark_images', ['id'], unique=False)
    op.create_table('pharaohs_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharaoh_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('image_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pharaoh_id'], ['pharaohs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharaohs_images_id'), 'pharaohs_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharaohs_images_id'), table_name='pharaohs_images')
    op.drop_table('pharaohs_images')
    op.drop_index(op.f('ix_landmark_images_id'), table_name='landmark_images')
    op.drop_table('landmark_images')
    op.drop_index(op.f('ix_pharaohs_id'), table_name='pharaohs')
    op.drop_table('pharaohs')
    op.drop_index(op.f('ix_landmarks_id'), table_name='landmarks')
    op.drop_table('landmarks')
    # ### end Alembic commands ###
