"""create pharaoh_texts and landmarks_text tables with hnsw indexes

Revision ID: 294c6ad06c3e
Revises: e11c7e071202
Create Date: 2026-03-03 20:41:50.609897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = '294c6ad06c3e'
down_revision: Union[str, None] = 'e11c7e071202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmarks_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('text_chunk', sa.Text(), nullable=True),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_idx_landmark_text_embedding', 'landmarks_texts', ['text_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'text_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_landmarks_texts_id'), 'landmarks_texts', ['id'], unique=False)
    op.create_table('pharaohs_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharaoh_id', sa.Integer(), nullable=True),
    sa.Column('text_chunk', sa.Text(), nullable=True),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['pharaoh_id'], ['pharaohs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_idx_pharaoh_text_embedding', 'pharaohs_texts', ['text_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'text_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_pharaohs_texts_id'), 'pharaohs_texts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharaohs_texts_id'), table_name='pharaohs_texts')
    op.drop_index('hnsw_idx_pharaoh_text_embedding', table_name='pharaohs_texts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'text_embedding': 'vector_cosine_ops'})
    op.drop_table('pharaohs_texts')
    op.drop_index(op.f('ix_landmarks_texts_id'), table_name='landmarks_texts')
    op.drop_index('hnsw_idx_landmark_text_embedding', table_name='landmarks_texts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'text_embedding': 'vector_cosine_ops'})
    op.drop_table('landmarks_texts')
    # ### end Alembic commands ###
