"""add gender column to pharaohs

Revision ID: 38c03f33938a
Revises: 5e97e760e4c6
Create Date: 2026-04-03 14:39:49.034648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c03f33938a'
down_revision: Union[str, None] = '5e97e760e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharaohs', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharaohs', 'gender')
    # ### end Alembic commands ###
