"""add type column to pharaohs

Revision ID: 5e97e760e4c6
Revises: 11bfd0bf7c97
Create Date: 2026-03-22 02:41:23.931794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e97e760e4c6'
down_revision: Union[str, None] = '11bfd0bf7c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharaohs', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharaohs', 'type')
    # ### end Alembic commands ###
