"""add landmark and pharaoh script embedding

Revision ID: bf1e22447449
Revises: 294c6ad06c3e
Create Date: 2026-03-04 16:20:22.375435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = 'bf1e22447449'
down_revision: Union[str, None] = '294c6ad06c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmarks_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('landmark_script', sa.Text(), nullable=True),
    sa.Column('landmark_script_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_idx_landmark_script_embedding', 'landmarks_scripts', ['landmark_script_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'landmark_script_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_landmarks_scripts_id'), 'landmarks_scripts', ['id'], unique=False)
    op.create_table('pharaohs_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharaoh_id', sa.Integer(), nullable=True),
    sa.Column('pharaoh_script', sa.Text(), nullable=True),
    sa.Column('pharaoh_script_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['pharaoh_id'], ['pharaohs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_idx_pharaoh_script_embedding', 'pharaohs_scripts', ['pharaoh_script_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'pharaoh_script_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_pharaohs_scripts_id'), 'pharaohs_scripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharaohs_scripts_id'), table_name='pharaohs_scripts')
    op.drop_index('hnsw_idx_pharaoh_script_embedding', table_name='pharaohs_scripts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'pharaoh_script_embedding': 'vector_cosine_ops'})
    op.drop_table('pharaohs_scripts')
    op.drop_index(op.f('ix_landmarks_scripts_id'), table_name='landmarks_scripts')
    op.drop_index('hnsw_idx_landmark_script_embedding', table_name='landmarks_scripts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'landmark_script_embedding': 'vector_cosine_ops'})
    op.drop_table('landmarks_scripts')
    # ### end Alembic commands ###
