"""add composite_entity column to pharaohs

Revision ID: e11c7e071202
Revises: 8949c77760fb
Create Date: 2026-03-02 16:22:22.497230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11c7e071202'
down_revision: Union[str, None] = '8949c77760fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharaohs', sa.Column('composite_entity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharaohs', 'composite_entity')
    # ### end Alembic commands ###
